### ISSUE TITLE
Fehlermeldung beim Deserialisieren

### ISSUE THREAD

**Issue by voltae** [bicoom/oom#101]
Ich bekommen immer eine hartnäckige Fehlermeldung beim Deserialiseren. Serialisieren funktioniert einwandfrei:
Der Compiler meckert wegen der Deserialisierung des Prices. Ich schicke das Log mit:
`Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].Price', line 6, position 14.
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDecimal()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor'1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Sports_equipment.Serialize.deserializeFromJSON(String JSONString, String filename) in /Users/marcaurel/Documents/Studium Technikum/BIC2/4_Objektorientierte_Methoden_Oeser/Projekte_C#/oom/tasks/Task4/SportsEquipment/SportsEquipment/Serialize.cs:line 30
   at Sports_equipment.Program.Main(String[] args) in /Users/marcaurel/Documents/Studium Technikum/BIC2/4_Objektorientierte_Methoden_Oeser/Projekte_C#/oom/tasks/Task4/SportsEquipment/SportsEquipment/Program.cs:line `

Ersten zwei Teile des Json:

[

  {
    "$type": "Sports_equipment.SportsItem, SportsEquipment",
    "Description": "Touren Ski",
    "Brand": "A45 670087",
    "Price": {
      "Amount": 295.95,
      "Unit": 3
    },
    "ArticleNumber": "Hagan"
  },
  {
    "$type": "Sports_equipment.SportsItem, SportsEquipment",
    "Description": "Football",
    "Brand": "B787 56333",
    "Price": {
      "Amount": 29.95,
      "Unit": 1
    },
    "ArticleNumber": "Adidas"
  },`

EDIT: Fehlermeldung hat sich jetzt geändert, das Json ist unverändert geblieben.

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got U. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Sports_equipment.Serialize.deserializeFromFilename(String filename) in /Users/marcaurel/Documents/Studium Technikum/BIC2/4_Objektorientierte_Methoden_Oeser/Projekte_C#/oom/tasks/Task4/SportsEquipment/SportsEquipment/Serialize.cs:line 40
   at Sports_equipment.Program.Main(String[] args) in /Users/marcaurel/Documents/Studium Technikum/BIC2/4_Objektorientierte_Methoden_Oeser/Projekte_C#/oom/tasks/Task4/SportsEquipment/SportsEquipment/Program.cs:line 45

**Comment by stefanmaierhofer** [comment]
JsonConvert.DeserializeObject erwartet als ersten Parameter einen String der JSON enthält!

```
static public IPrint[] deserializeFromFilename (string filename)
{
    var filepath = Serialize.filePathToDesktopFromName(filename);

    var fileFromText = File.ReadAllText(filepath);
    IPrint[] objects = JsonConvert.DeserializeObject<IPrint[]>(filepath, settings);

    return objects;
}
```

**Comment by stefanmaierhofer** [comment]
... danach kommt noch ein weiterer Parse-Error, weil DeserializeObject keinen passenden SportsItem-Constructor findet ...

**Comment by voltae** [comment]
Danke, der erste Fehler ist mir klar, ich habe einfach statt dem tatsächlichen file, den Filenamen in die Deserialisiermethode gestopft. 
Der zweite Fehler, der hauptsächliche ist mir nicht klar, da die Klasse SportItem ja einen Konstruktor hat.
``` /* SportsItem - Constructor */
        public SportsItem (String newDescription, String newArticleNumber, String newBrand,  decimal price, Currency currency)
        {
            Brand = newBrand;
            ArticleNumber= newArticleNumber;
            
            Description = newDescription;
            /* casting the double to decimal in one single point */
            Price = new Price(price, currency);

        }
Welchen Konstruktor erwartet sich die Deserializierfunktion?

**Comment by stefanmaierhofer** [comment]
Im JSON ist das "Price"-Feld ein Price (mit Amount und Unit), der Konstruktor nimmt aber zwei separate Parameter "decimal price" und "Currency currency"). Der Deserializer versteht nicht wie er das
```
"Price": {
      "Amount": 295.95,
      "Unit": 3
    },
```
dem Constructor

`public SportsItem (String newDescription, String newArticleNumber, String newBrand,  decimal price, Currency currency)`

übergeben soll.


```
{
    "$type": "Sports_equipment.SportsItem, SportsEquipment",
    "Description": "Touren Ski",
    "Brand": "A45 670087",
    "Price": {
      "Amount": 295.95,
      "Unit": 3
    },
    "ArticleNumber": "Hagan"
  }
```

**Comment by voltae** [comment]
Ah, klar eigentlich, jetzt. Danke funktioniert alles. Hab noch einen Testcase eingefügt der das serialisieren testet.
Frohe Ostern!
