### ISSUE TITLE
read json Problem

### ISSUE THREAD

**Issue by rkerschbaumer** [bicoom/oom#45]
.json file wird korrekt auf die Festplatte geschrieben, allerdings kann ich es nicht mehr einlesen --> trotz mehrmaligen Vergleichs mit "lesson 4" Beispiel.

**Comment by ChristianMoe** [comment]
wie sieht dein Code aus? ist der Filename der gleiche?

**Comment by ChristianMoe** [comment]
Habe mir deinen Code kurz angesehen. Ich komm leider auch nicht drauf warum es nicht funktioniert. Sorry.

**Comment by bicoom** [comment]
Was bedeutet "allerdings kann ich es nicht mehr einlesen"?
* Der File-Inhalt kann von File.ReadAllText nicht gelesen werden?
* Der json-string kann mit JsonConvert.DeserializeObject nicht deserialisiert werden?

Gibt es eine Exception? Wenn ja, welche?

lg

**Comment by bicoom** [comment]
Falls es folgende Exception gibt:

```
Newtonsoft.Json.JsonReaderException was unhandled
  HResult=-2146233088
  LineNumber=8
  LinePosition=14
  Message=Unexpected character encountered while parsing value: {. Path '[0].Price', line 8, position 14.
  Path=[0].Price
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
       at Newtonsoft.Json.JsonTextReader.ReadAsDecimal()
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at Task4.Program.SerializeDisks(IEnumerable`1 disks) in c:\Data\Development\tmp\oom\tasks\Task4\Task4\Program.cs:line 40
       at Task4.Program.Main(String[] args) in c:\Data\Development\tmp\oom\tasks\Task4\Task4\Program.cs:line 26
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Comment by bicoom** [comment]
... dann sieht man an der angegebenen Position eine öffnende geschwungene Klammer `{`,  gleich nach **` "Price":`**.

```
[
  {
    "$type": "Task4.CompactDisk, Task4",
    "Bandname": "Slayer ",
    "Diskname": "Repentless",
    "ASIN": "B00ZU6IVXW",
    "Description": "CD Slayer Repentless",
    "Price": {
      "Amount": 21.99,
      "Unit": 0
    }
  },
...
```

**Comment by bicoom** [comment]
... im Stacktrace sieht man, dass der Serializer aber scheinbar versucht einen `decimal` zu lesen:

`at Newtonsoft.Json.JsonTextReader.ReadAsDecimal()`

**Comment by bicoom** [comment]
... schaut man sich die Klasse `CompactDisk` näher an, dann sieht man einerseits das public Property `public myPrice Price => actualprice;`, welches serialisiert wird, als 
```
"Price": {
      "Amount": 21.99,
      "Unit": 0
    }
```

**Comment by bicoom** [comment]
... der Constructor von CompactDisk (den natürlich auch der Deserializer verwendet)

`public CompactDisk(string bandname, string diskname, decimal price, Currency curr, string asin )`

hat ein Argument das ebenfalls `price` heisst, aber als Typ `decimal` hat (die Währung wird getrennt im nächsten Argument `curr` übergeben.

Hier kennt sich dann der Deserializer nicht mehr aus ...

**Comment by bicoom** [comment]
... aus diesem Grund gibt es in https://github.com/bicoom/oom/blob/master/lessons/lesson4/lesson4/Book.cs auch einen Constructor `public Book(string title, string isbn, Price price)`.

Dieser ist mit mit `[JsonConstructor]` gekennzeichnet - damit gibt man dem Serializer den Hinweis welcher Constructor verwendet werden soll.

Alternativ könnte man den anderen Constructor auch löschen - der Serializer verwendet dann wieder den einzig vorhandenen, aber in diesem Fall den richtigen. Allerdings müsste man dann auch alle Aufrufe im Rest des Programms anpassen.

lg

**Comment by rkerschbaumer** [comment]
Danke! 
mir hat der zweite Constructor gefehlt, jetzt ist es mir auch klar warum es nicht funktioniert hat! 
einige kleine Änderungen im Code waren sonst auch noch Notwendig.
(Danke auch an Christian für die Mühe über meinen Code rüberzuschauen).

jedenfalls läuft das Programm jetzt. :)
lg
