### ISSUE TITLE
json DeserializeObject

### ISSUE THREAD

**Issue by twpatrick** [bicoom/oom#86]
Folgenden Code habe ich: 

            var dvd1 = new Dvd("Dr. House - Staffel 1", 12.99m, Currency.EUR, new DateTime(2006, 12, 24), 925);

            Console.WriteLine(JsonConvert.SerializeObject(dvd1, Formatting.Indented));

            var settings = new JsonSerializerSettings() { Formatting = Formatting.Indented, TypeNameHandling = TypeNameHandling.Auto };
            Console.WriteLine(JsonConvert.SerializeObject(dvd1, settings));

            var text = JsonConvert.SerializeObject(dvd1,settings);
            var desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
            var filename = Path.Combine(desktop, "dvd.json");
            File.WriteAllText(filename, text);

            var textFromFile = File.ReadAllText(filename);
            var dvd2 = JsonConvert.DeserializeObject<Dvd>(textFromFile,settings);
            Console.WriteLine("Titel ist: " + dvd2.Title);

Allerdings taucht beim ausführen der Zeile mit JsonConvert.DeserializeObject... folgender Fehler auf: 

```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Price', line 4, position 12.
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDecimal()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Task4.Program.json() in C:\Technikum\2. Semester\Objektorientierte Methoden\OOD\oom\tasks\Task4\Task4\Task4\Program.cs:line 35
   at Task4.Program.Main(String[] args) in C:\Technikum\2. Semester\Objektorientierte Methoden\OOD\oom\tasks\Task4\Task4\Task4\Program.cs:line 17
```

Auf meinem Desktop wird eine dvd.json erstellt, die auch das Objekt enthält. 

Was mache ich falsch?

**Comment by bicoom** [comment]
Problembeschreibung und Lösung, siehe https://github.com/bicoom/oom/issues/45

**Comment by twpatrick** [comment]
Danke, angepasst und funktioniert. 
Issue kann geschlossen werden.
