### ISSUE TITLE
Error with deserialization of JSON File in LatestTask Program.cs Line 66

### ISSUE THREAD

**Issue by ic16b075** [bicoom/oom#96]
Hallo,

Ich kann mein JSON File nicht deserialisieren. Aktueller Code wurde ins Github gepusht. Es geht um das Projekt LatestTask.
Bevor das Programm abstürzt bekomme ich folgende Fehlermeldung in der cmd:

`
Unhandled Exception: System.ArgumentException: Title must not be empty!
Parameter name: new_title
   at LatestTask.Film..ctor(String new_title, Double new_price, Decimal new_release_year, Boolean new_status) in C:\Users\e\Documents\oom\tasks\LatestTask\LatestTask\LatestTask\Film.cs:line 19
   at Void .ctor(System.String, Double, System.Decimal, Boolean)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at LatestTask.MainCLass.Main(String[] args) in C:\Users\e\Documents\oom\tasks\LatestTask\LatestTask\LatestTask\Program.cs:line 66
`

**Comment by bicoom** [comment]
Hallo,

kann es sein, dass die Parameter im Constructor andere Namen haben als die serialisierten Properties?

Siehe auch https://github.com/bicoom/oom/wiki/Lesson-4:
You should name constructor parameters like the serialized properties - this helps DeserializeObject library to correctly map JSON fields to constructor parameters.

// Parameter names map to JSON fields "Title", "ISBN", and "Price".
public Book(string title, string isbn, Price price) { ... }

**Comment by ic16b075** [comment]
Domo arigato,

Genau das war der Fehler!

Ich stehe tief in ihrer Schuld, Sensei.
